[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-http = "3.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 
actix = "0.13.5"
actix-web-actors = "4.3.1"
# uuid = { version = "1", features = ["v4", "serde"] }