FROM node:23-alpine AS base

WORKDIR /app

COPY package.json ./
COPY server.cjs ./

RUN npm i

# Install ffmpeg using Alpine's package manager
RUN apk add --no-cache ffmpeg

CMD ["node", "server.cjs"]